name = "DualSDDP"
uuid = "7f8d178f-c40c-4e8c-bfb1-3d30c9997f30"
authors = ["Bernardo Freitas Paulo da Costa <bernardofpc@im.ufrj.br>",
           "Vincent Lecl√®re <vincent.leclere@enpc.fr>"
          ]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
